name: Docker Image CI

on: [push]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker login -u Goblinmaster -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker buildx create --use
          docker buildx build .   --push --tag Goblinmaster/island:front
